<?
$language_admin = array(

'index.title' => 'Panel de Administrador',
'index.server_time' => 'Hora del Servidor',
'index.logout' => '[Desconectar]',

'login.pass_sent' => 'Contraseña enviada al email de administrador',
'login.invalid_login' => 'Datos incorrectos',
'login.username' => 'Nombre de Usuario',
'login.password' => 'Contraseña',
'login.button_login' => 'Entrar',
'login.button_send' => 'Recuperar contraseña',

'default.stats_title' => 'Estadísticas del sitio',
'default.last_day' => 'Publicados en las últimas 24 horas',
'default.ads_total' => 'Anuncios en Total',
'default.ads_premium1' => 'Anuncios Destacados Portada',
'default.ads_premium2' => 'Anuncios Destacados Listado',
'default.user_total' => 'Usuarios registrados',

'param_config.save_changes' => 'Datos de configuración guardados.',
'param_config.site_config' => 'Configuración del sitio',
'param_config.site_details' => 'Datos de tu sitio',
'param_config.ads_config' => 'Configuración de anuncios',
'param_config.social_pages' => 'Perfiles en Redes',
'param_config.button_save' => 'Guardar Configuración',

'admin_user.saved' => 'Datos actualizados',
'admin_user.title_h1' => 'Administrador',
'admin_user.username' => 'Nombre de Usuario',
'admin_user.mail' => 'Email del administrador',
'admin_user.password' => 'Contraseña',
'admin_user.button_save' => 'Actualizar Datos',

'backup.title_h1' => 'Copia de Seguridad',
'backup.deleted_backup' => 'Se ha eliminado correctamente una copia de seguridad de la base de datos',
'backup.created_backup' => 'Se ha generado correctamente una copia de seguridad de la base de datos',
'backup.info_backup' => 'Puedes realizar una copia de seguridad de la base de datos en cualquier momento. Y se descargara al instante.<br/>
Para generar una copia de seguridad de la base de datos en este momento haz click en Generar.<br /><br/>',
'backup.button_generate' => 'Generar Copia de Seguridad',
'backup.title_h3' => 'Copias de Seguridad realizadas',
'backup.download' => 'Descargar',
'backup.delete' => 'Borrar',

'banner.banner_saved' => 'Banner guardado correctamente.',
'banner.label_code' => 'Código del Banner',
'banner.button_save' => 'Guardar',
'banner.link_back' => 'VOLVER A BANNERS',
'banner.title_h1' => 'Gestión de Banners',
'banner.edit_banner' => 'Modificar',

'manage_premium.config_saved' => 'Configuración actualizada',
'manage_premium.title_h1' => 'Gestionar Pagos',
'manage_premium.label_mail' => 'Email PayPal',
'manage_premium.label_currency' => 'Recibir pagos en',
'manage_premium.select_currency' => 'Seleccione',
'manage_premium.price1' => 'Precio Destacado en Portada',
'manage_premium.time1' => 'Duración Destacado en Portada (Días)',
'manage_premium.price2' => 'Precio Destacado en Listado',
'manage_premium.time2' => 'Duración Destacado en Listado (Días)',
'manage_premium.button_save' => 'Actualizar Datos',
//new
'manage_premium.time_price_banner' => 'Duración y Precio Banner',
'manage_premium.time_price_premium' => 'Duración y Precio Premium',
'manage_premium.price_credit' => 'Precio del credito',
'manage_premium.adult_title' => 'TARIFAS ADULTOS',

'manage_region.title_h1' => 'Gestionar Regiones',
'manage_region.add_city' => 'Añadir Localidad',
'manage_region.send' => 'Enviar',
'manage_region.edit' => 'Editar',
'manage_region.delete' => 'Borrar',
'manage_region.back_region' => 'VOLVER A PROVINCIAS',
'manage_region.edit_city' => 'Modificar Localidad',
'manage_region.button_add' => 'Añadir',
'manage_region.button_save' => 'Modificar',
'manage_region.back_city' => 'VOLVER A LOCALIDADES',
'manage_region.add_region' => 'Añadir Provincia',
'manage_region.view_cities' => 'Ver Localidades',
'manage_region.edit_region' => 'Modificar Provincia',
'manage_region.city_deleted' => 'Localidad eliminada correctamente.',
'manage_region.city_created' => 'Localidad creada correctamente.',
'manage_region.city_edited' => 'Localidad modificada correctamente.',
'manage_region.region_deleted' => 'Provincia eliminada correctamente.',
'manage_region.region_created' => 'Provincia creada correctamente.',
'manage_region.region_edited' => 'Provincia modificada correctamente.',

'manage_categories.title_h1' => 'Gestionar Categorías',
'manage_categories.title_h1_2' => 'Gestionar Subcategorías',
'manage_categories.add_subcat' => 'Añadir Subcategoría',
'manage_categories.seo_title' => 'Título SEO',
'manage_categories.seo_desc' => 'Descripción SEO',
'manage_categories.seo_keys' => 'Keywords SEO',
'manage_categories.price_label' => 'Precio por publicar',
'manage_categories.send' => 'Enviar',
'manage_categories.edit' => 'Editar',
'manage_categories.delete' => 'Borrar',
'manage_categories.back_cat' => 'VOLVER A CATEGORÍAS',
'manage_categories.edit_subcat' => 'Modificar Subcategorías',
'manage_categories.button_add' => 'Añadir',
'manage_categories.button_save' => 'Modificar',
'manage_categories.back_subcat' => 'VOLVER A SUBCATEGORÍAS',
'manage_categories.add_cat' => 'Añadir Categorías',
'manage_categories.view_subcat' => 'Ver Subcategorías',
'manage_categories.edit_cat' => 'Modificar Categoría',
'manage_categories.subcat_deleted' => 'Subcategoría eliminada correctamente.',
'manage_categories.subcat_created' => 'Subcategoría creada correctamente.',
'manage_categories.subcat_edited' => 'Subcategoría modificada correctamente.',
'manage_categories.cat_deleted' => 'Categoría eliminada correctamente.',
'manage_categories.cat_created' => 'Categoría creada correctamente.',
'manage_categories.cat_edited' => 'Categoría modificada correctamente.',
'manage_categories.orden' => 'Orden de Aparición',

'manage_user.user_deleted' => 'Usuario eliminado',
'manage_user.title_h1' => 'Listado de Usuarios',
'manage_user.search_user' => 'Buscar usuario',
'manage_user.id_user' => 'ID usuario',
'manage_user.mail' => 'Email',
'manage_user.export_user' => 'Exportar Usuarios',
'manage_user.button_search' => 'Buscar usuario',
'manage_user.total_user' => 'Total Usuarios',
'manage_user.info_user' => 'Información del Usuario',
'manage_user.opt_user' => 'Opciones',
'manage_user.no_date' => 'No consta',
'manage_user.view_ads' => 'Ver Anuncios',
'manage_user.delete_user_ads' => 'Eliminar usuario y anuncios',
'manage_user.block_user' => 'Impedir Acceso',
'manage_user.unblock_user' => 'Permitir Acceso',
'manage_user.add_credits' => 'Agregar Créditos',


'manage_item.ad_deleted' => 'Anuncio eliminado.',
'manage_item.ad_renoved' => 'Anuncio renovado.',
'manage_item.ad_actived' => 'Anuncio validado.',
'manage_item.ad_premium2' => 'Anuncio destacado en listado.',
'manage_item.ad_premium1' => 'Anuncio destacado en portada.',
'manage_item.ad_not_premium2' => 'Anuncio no destacado en listado.',
'manage_item.ad_not_premium1' => 'Anuncio no destacado en portada.',
'manage_item.ads_deleted' => ' anuncios eliminados.',
'manage_item.ads_renoved' => ' anuncios renovados.',
'manage_item.ads_actived' => ' anuncios validados.',
'manage_item.title_h1' => 'Gestionar Anuncios',
'manage_item.of' => ' de ',
'manage_item.ads' => 'anuncios',
'manage_item.all_ads' => 'Todos los anuncios',
'manage_item.ads_to_review' => 'Anuncios por validar',
'manage_item.col_photo' => 'Foto',
'manage_item.col_info' => 'Información',
'manage_item.col_opt' => 'Opciones',
'manage_item.in' => ' en ',
'manage_item.post_since' => 'Hace ',
'manage_item.no_price' => 'A consultar',
'manage_item.opt_validate' => 'Validar Anuncio',
'manage_item.opt_premium1' => 'Destacar Premium',
'manage_item.opt_not_premium1' => 'No Destacar Premium',
'manage_item.opt_premium2' => 'Subir al Listado',
'manage_item.opt_not_premium2' => 'No Subir al Listado',
'manage_item.opt_renove' => 'Renovar Gratis',
'manage_item.opt_edit' => 'Editar',
'manage_item.opt_delete' => 'Eliminar',
'manage_item.multiple_choices' => 'Para los elementos seleccionados',
'manage_item.multiple_delete' => 'Eliminar',
'manage_item.multiple_renove' => 'Renovar',
'manage_item.multiple_active' => 'Validar',
'manage_item.button_aply' => 'Aplicar',

);
?>