<div class="col_single">
    <h1>Aviso Legal</h1>
    <div class="terms">
        <p>Con los límites establecidos en la ley, <?= getConfParam('SITE_NAME')?> no asume ninguna responsabilidad derivada de la falta de veracidad, integridad, actualización y precisión de los datos o informaciones que contienen sus páginas web.</p>
        <p>Los contenidos e información no vinculan a Solomasajistas.com ni constituyen opiniones, consejos o asesoramiento de ningún tipo.</p>
        <p>Adriana Do Nascimento Rego (en adelante Solomasajistas.com ) , con NIF nº: 26335260F y dirección en: C/ Industria, 132, 08025- Barcelona (Barcelona), no puede asumir ninguna responsabilidad derivada del uso incorrecto, inapropiado o ilícito de la información aparecida en la página de solomasajistas.com</p>
        <p>Las páginas de Internet de Solomasajistas.com pueden contener enlaces (links) a otras páginas de terceras partes que Solomasajistas.com no puede controlar. Por lo tanto, Solomasajistas.com no puede asumir responsabilidades por el contenido que pueda aparecer en páginas de terceros.</p>
        <p>Los textos, imágenes, sonidos, animaciones, software y el resto de contenidos incluidos en este website son propiedad exclusiva de Solomasajistas.com o sus anunciantes. Cualquier acto de transmisión, distribución, cesión, reproducción, almacenamiento o comunicación pública total o parcial, deberá contar con el consentimiento expreso de Solomasajistas.com.</p>
        <p>Asimismo, para acceder a algunos de los servicios que Solomasajistas.com ofrece a través del sitio web, deberá proporcionar algunos datos de carácter personal. En cumplimiento de lo establecido en el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos le informamos que, mediante la cumplimentación de los presentes formularios, sus datos personales quedarán incorporados y serán tratados en los ficheros de Solomasajistas.com con el fin de poderle prestar y ofrecer nuestros servicios así como para informarle de las mejoras del sitio Web.</p>
        <p>Le informamos también de que tendrá la posibilidad en todo momento de ejercer los derechos de acceso, rectificación, cancelación, oposición, limitación y portabilidad de sus datos de carácter personal, de manera gratuita mediante email <a style="color: #175d17; font-weight: 400;" href="contactar">info@solomasajistas.com</a></p>
    </div>
</div>